site_name: 'python-app-5'
site_description: 'Main documentation for the python-app-5'
repo_url: https://github.com/l-v-b/python-app-5
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
    - Getting Started: 'docs/index.md'
